### ISSUE TITLE
When clicking the download link from Firefox on Mac it downloads the Linux client.

### ISSUE THREAD

**Issue by herunan** [dothq/dothq.co#16]

**Comment by EnderDev** [comment]
We'll look into this for you.

**Comment by EnderDev** [comment]
This should be fixed.

**Comment by ArashNrIm** [comment]
Hey there!

Thanks for creating the Dot products of things and deciding to make them open-sourced! I noticed that this issue still persists on my end, running Firefox 78.0.1 as well. I noticed that the website failed to read the OS (macOS) and all the download buttons simply appear as "Download for"; take a look at the screenshots below.

<img width="1403" alt="Screenshot 2020-07-05 at 1 55 35 PM" src="https://user-images.githubusercontent.com/47273556/86526492-25f51280-be84-11ea-807c-04a2e6b43fe0.png">

<img width="1403" alt="Screenshot 2020-07-05 at 1 55 56 PM" src="https://user-images.githubusercontent.com/47273556/86526497-33aa9800-be84-11ea-9765-62513c5f10d7.png">

I've tried this on my alternate Browser, Brave (Chromium, I guess), and it works just fine there. I'm guessing this has something to do with just Firefox, then. Safari works fine as well. Hope this helps!

**Comment by AwesomeTech10** [comment]
Hey, can you tell us what your user agent string is?

**Comment by ArashNrIm** [comment]
Sure thing. Not too sure if this is what you're looking for, but I managed to get this:
` Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 `

Weirdly, though, I'm running macOS.

**Comment by AwesomeTech10** [comment]
> Sure thing. Not too sure if this is what you're looking for, but I managed to get this:
> ` Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 `
> 
> Weirdly, though, I'm running macOS.

The problem is, your user agent string (which is how we figure out what operating system you are using) doesn't specify what OS you have for some reason. I can test this and figure out why Firefox does this, though.

**Comment by AwesomeTech10** [comment]
I have a few questions for you @ArashNrIm.

- What version of macOS are you using?
- Have you ever messed with the user agent before?

**Comment by ArashNrIm** [comment]
Hey @AwesomeTech10,

I'm using macOS 10.15.5 (Catalina) at the moment.

I believe you raised a valid point regarding messing with the user agent, though; I had tweaked some settings in Firefox's ` about:config ` page. I refreshed Firefox (reset everything back to their initial conditions), but it seems that this issue still hasn't resolved.

Hope this helps!

**Comment by AwesomeTech10** [comment]
I have a Catalina machine I can borrow, so I am going to install Firefox and see if I can figure out what is causing this.

**Comment by ArashNrIm** [comment]
Just a small update here: since refreshing Firefox, it appears that the user agent string has changed back to what (at least) I expected:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0`

It appears that there's a few [browser settings](https://support.mozilla.org/en-US/kb/how-reset-default-user-agent-firefox) that may change this; in my case, I had `privacy.resistFingerprinting` enabled.

When taking a look at the [website](dothq.co) again, though (through normal and Private Browsing windows), it seems that the same thing happens again; macOS wasn't picked up.

**Comment by EnderDev** [comment]
Strange, I'll keep looking into this for you.

**Comment by AwesomeTech10** [comment]
I've actually been doing some testing, and yes, there is a problem with this. I'll see why it isn't detecting macOS. Thank you for bringing this to our attention!On Jul 6, 2020 4:50 AM, Arash <notifications@github.com> wrote:
Just a small update here: since refreshing Firefox, it appears that the user agent string has changed back to what (at least) I expected:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0
It appears that there's a few browser settings that may change this; in my case, I had privacy.resistFingerprinting enabled.
When taking a look at the website again, though (through normal and Private Browsing windows), it seems that the same thing happens again; macOS wasn't picked up.
